site_name: "Sclera Documentation"

site_description: "Documentation for Sclera and its plugins"

site_author: "Sclera, Inc."

copyright: "Copyright &copy; 2012 - 2020 Sclera, Inc."

site_url: "https://www.scleradb.com/docs"

repo_url: "https://github.com/scleradb/sclera-website"

site_dir: docs

docs_dir: docsrc

nav:
    - Home: "/"
    - Introduction: index.md
    - Overview: overview.md
    - FAQ: faq.md

theme:
    name: "material"
    logo: "../images/sclera-logo-square.png"
    favicon: "../images/icons/favicon.ico"

extra:
    social:
        - type: "github"
          link: "https://github.com/scleradb"
        - type: "twitter"
          link: "https://twitter.com/scleradb"
        - type: "linkedin"
          link: "https://www.linkedin.com/company/sclera-inc-"
    manifest: "../images/icons/site.webmanifest"
