site_name: Sclera Documentation

site_url: https://www.scleradb.com/docs

site_dir: docs

docs_dir: docsrc

nav:
    - Home: "/"
    - Introduction: index.md
    - Overview: overview.md
    - FAQ: faq.md

theme:
    name: 'material'
